-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Création du schéma
------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE SCHEMA IDENTIFIER('"ANALYSE_IMMO_PARIS_2022"."SCHEMA"') COMMENT = ''

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Création du schéma 
------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Duplication de VALEURS_FONCIERES
CREATE TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES AS
SELECT * FROM ANALYSE_IMMO_PARIS_2022.PUBLIC.VALEURS_FONCIERES;

ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES
ADD ID_ARRONDISSEMENT NUMBER(38,0);

UPDATE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES F
SET F.ID_ARRONDISSEMENT = A.IDENTIFIANT_SEQUENTIEL_ARRONDISSEMENT
FROM ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_ARRONDISSEMENTS A
WHERE F.NUMERO_ARRONDISSEMENT_INSEE = A.NUMERO_ARRONDISSEMENT_INSEE;

------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Duplication de ENCADREMENT_DES_LOYERS
CREATE TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS AS
SELECT * FROM ANALYSE_IMMO_PARIS_2022.PUBLIC.ENCADREMENT_DES_LOYERS;

ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS
ADD ID_ARRONDISSEMENT NUMBER(38,0);

UPDATE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS F
SET F.ID_ARRONDISSEMENT = A.IDENTIFIANT_SEQUENTIEL_ARRONDISSEMENT
FROM ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_ARRONDISSEMENTS A
WHERE F.NUMERO_ARRONDISSEMENT = A.NUMERO_ARRONDISSEMENT;

------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Duplication de ARRONDISSEMENTS
CREATE TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_ARRONDISSEMENTS AS
SELECT * FROM ANALYSE_IMMO_PARIS_2022.PUBLIC.ARRONDISSEMENTS;

ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_ARRONDISSEMENTS
RENAME COLUMN IDENTIFIANT_SEQUENTIEL TO IDENTIFIANT_SEQUENTIEL_ARRONDISSEMENT;

ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES
ADD ID_ARRONDISSEMENT NUMBER(38,0);

------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Duplication de QUARTIERS_ADMINISTRATIFS
CREATE TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_QUARTIERS_ADMINISTRATIFS AS
SELECT * FROM ANALYSE_IMMO_PARIS_2022.PUBLIC.QUARTIERS_ADMINISTRATIFS;

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Création de la table de dimension DIM_DATE
CREATE TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_DATE AS
SELECT DISTINCT DATE_MUTATION
FROM ANALYSE_IMMO_PARIS_2022.SCHEMA.FACT_VALEURS_FONCIERES;

-- Créer une nouvelle table temporaire avec une colonne auto-incrémentée
CREATE OR REPLACE TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.TEMP_DIM_DATE AS
SELECT
  ROW_NUMBER() OVER (ORDER BY DATE_MUTATION) AS ID_DATE,
  DATE_MUTATION
FROM ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_DATE;

-- Ajouter la colonne auto-incrémentée à la table existante
ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_DATE
ADD COLUMN ID_DATE NUMBER(38, 0);

-- Mettre à jour la table existante avec les valeurs auto-incrémentées
MERGE INTO ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_DATE D
USING ANALYSE_IMMO_PARIS_2022.SCHEMA.TEMP_DIM_DATE T
ON D.DATE_MUTATION = T.DATE_MUTATION
WHEN MATCHED THEN UPDATE SET D.ID_DATE = T.ID_DATE;

-- Supprimer la table temporaire
DROP TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.TEMP_DIM_DATE;

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Création de la table de dimension DIM_TYPE_LOCAL
CREATE TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_TYPE_LOCAL AS
SELECT DISTINCT TYPE_LOCAL, ID_VALEURS_FONCIERES
FROM ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES;

-- Renommage ID_DATE côté DIM_TYPE_LOCAL
ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_TYPE_LOCAL
RENAME COLUMN ID_VALEURS_FONCIERES TO ID_TYPE_LOCAL;

-- Création de la colonne ID_TYPE_LOCAL
ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES
ADD COLUMN ID_TYPE_LOCAL NUMBER(38,0);

UPDATE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES
SET ID_TYPE_LOCAL = ID_VALEURS_FONCIERES;

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Création de la table DIM_ADRESSE
CREATE TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_ADRESSE AS
SELECT DISTINCT ADRESSE_NUMERO,ADRESSE_NOM_VOIE,VOIE,CODE_POSTAL, ID_VALEURS_FONCIERES
FROM ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES;

ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_ADRESSE 
RENAME COLUMN ID_VALEURS_FONCIERES TO ID_ADRESSE ;

ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES
ADD COLUMN ID_ADRESSE NUMBER(38,0);

UPDATE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES
SET ID_ADRESSE = ID_VALEURS_FONCIERES;

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Création de la table DIM_TYPE_LOCATION 

CREATE TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_TYPE_LOCATION AS
SELECT DISTINCT TYPE_DE_LOCATION, ID_TYPE_LOCATION
FROM ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS;

ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS
ADD COLUMN ID_TYPE_LOCATION NUMBER(38,0);

UPDATE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS
SET ID_TYPE_LOCATION = ID_ENCADREMENT_DES_LOYERS;


-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Création de la table DIM_EPOQUE_DE_CONSTRUCTION

CREATE TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_EPOQUE_DE_CONSTRUCTION AS
SELECT DISTINCT EPOQUE_DE_CONSTRUCTION, ID_EPOQUE_DE_CONSTRUCTION
FROM ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS;

ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS
ADD COLUMN ID_EPOQUE_DE_CONSTRUCTION NUMBER(38,0);

UPDATE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS
SET ID_EPOQUE_DE_CONSTRUCTION = ID_ENCADREMENT_DES_LOYERS;


-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Création des clés primaires
------------------------------------------------------------------------------------------------------------------------------------------------------------

ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES ADD CONSTRAINT FAIT_VALEURS_FONCIERES_PK PRIMARY KEY (ID_VALEURS_FONCIERES);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_DATE ADD CONSTRAINT DIM_DATE_PK PRIMARY KEY (ID_DATE);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_EPOQUE_DE_CONSTRUCTION ADD CONSTRAINT DIM_EPOQUE_DE_CONSTRUCTION_PK PRIMARY KEY (ID_EPOQUE_DE_CONSTRUCTION);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_TYPE_LOCAL ADD CONSTRAINT DIM_TYPE_LOCAL_PK PRIMARY KEY (ID_TYPE_LOCAL);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_TYPE_LOCATION ADD CONSTRAINT DIM_TYPE_LOCATION_PK PRIMARY KEY (ID_TYPE_LOCATION);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_ADRESSE ADD CONSTRAINT DIM_ADRESSE_PK PRIMARY KEY (ID_ADRESSE);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_ARRONDISSEMENTS ADD CONSTRAINT DIM_ARRONDISSEMENTS_PK PRIMARY KEY (IDENTIFIANT_SEQUENTIEL);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_QUARTIERS_ADMINISTRATIFS ADD CONSTRAINT DIM_QUARTIERS_ADMINISTRATIFS_PK PRIMARY KEY (NUMERO_SEQUENTIEL_QUARTIER);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_NBR_PIECES ADD CONSTRAINT DIM_NBR_PIECES_PK PRIMARY KEY (ID_NOMBRE_DE_PIECES_PRINCIPALES);

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Création des clés étrangères
------------------------------------------------------------------------------------------------------------------------------------------------------------

ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES ADD CONSTRAINT FAIT_VALEURS_FONCIERES_PK PRIMARY KEY (ID_VALEURS_FONCIERES);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES ADD CONSTRAINT FAIT_VALEURS_FONCIERES_DIM_ADRESSES_FK FOREIGN KEY (ID_ADRESSE) REFERENCES ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_ADRESSES(ID_ADRESSE);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES ADD CONSTRAINT FAIT_VALEURS_FONCIERES_DIM_ARRONDISSEMENTS_FK FOREIGN KEY (IDENTIFIANT_SEQUENTIEL_ARRONDISSEMENT) REFERENCES ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_ARRONDISSEMENTS(IDENTIFIANT_SEQUENTIEL_ARRONDISSEMENT);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES ADD CONSTRAINT FAIT_VALEURS_FONCIERES_DIM_DATE_FK FOREIGN KEY (ID_DATE) REFERENCES ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_DATE(ID_DATE);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES ADD CONSTRAINT FAIT_VALEURS_FONCIERES_DIM_TYPE_LOCAL_FK FOREIGN KEY (ID_TYPE_LOCAL) REFERENCES ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_TYPE_LOCAL(ID_TYPE_LOCAL);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES ADD CONSTRAINT FAIT_VALEURS_FONCIERES_DIM_NBR_PIECES_FK FOREIGN KEY (ID_NOMBRE_DE_PIECES_PRINCIPALES) REFERENCES ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_NBR_PIECES(ID_NOMBRE_DE_PIECES_PRINCIPALES);

ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS ADD CONSTRAINT FK_ARRONDISSEMENT FOREIGN KEY (ID_ARRONDISSEMENT) REFERENCES ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_ARRONDISSEMENTS(IDENTIFIANT_SEQUENTIEL_ARRONDISSEMENT);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_LOYERS ADD CONSTRAINT FAIT_ENCADREMENT_LOYERS_DIM_TYPE_DE_LOCATION_FK FOREIGN KEY (ID_TYPE_DE_LOCATION) REFERENCES ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_TYPE_DE_LOCATION(ID_TYPE_DE_LOCATION);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_LOYERS ADD CONSTRAINT FAIT_ENCADREMENT_LOYERS_DIM_NBR_PIECES_FK FOREIGN KEY (ID_NOMBRE_DE_PIECES_PRINCIPALES) REFERENCES ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_NBR_PIECES(ID_NOMBRE_DE_PIECES_PRINCIPALES);
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_LOYERS ADD CONSTRAINT FAIT_ENCADREMENT_LOYERS_DIM_EPOQUE_DE_CONSTRUCTION_FK FOREIGN KEY (ID_EPOQUE_DE_CONSTRUCTION) REFERENCES ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_EPOQUE_DE_CONSTRUCTION(ID_EPOQUE_DE_CONSTRUCTION);

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Ajustement sur l'année FAIT_ENCADREMENT_DES_LOYERS
------------------------------------------------------------------------------------------------------------------------------------------------------------

DELETE FROM ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS
WHERE ANNEE <> 2022;

ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_ENCADREMENT_DES_LOYERS
DROP COLUMN ANNEE;

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Ajustement sur la nature de mutation FAIT_VALEURS_FONCIERES
------------------------------------------------------------------------------------------------------------------------------------------------------------

DELETE FROM ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES
WHERE NATURE_MUTATION <> 'Vente';

ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.FAIT_VALEURS_FONCIERES
DROP COLUMN NATURE_MUTATION;

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Suppression des colonnes inutiles
------------------------------------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES DROP COLUMN DATE_MUTATION;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES DROP COLUMN ADRESSE_NUMERO;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES DROP COLUMN ADRESSE_NOM_VOIE;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES DROP COLUMN VOIE;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES DROP COLUMN CODE_POSTAL;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES DROP COLUMN TYPE_LOCAL;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_VALEURS_FONCIERES DROP COLUMN NUMERO_ARRONDISSEMENT_INSEE;

ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_DES_LOYERS DROP COLUMN SECTEURS_GEOGRAPHIQUES;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_DES_LOYERS DROP COLUMN NUMERO_DU_QUARTIER;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_DES_LOYERS DROP COLUMN NOM_DU_QUARTIER;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_DES_LOYERS DROP COLUMN EPOQUE_DE_CONSTRUCTION;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_DES_LOYERS DROP COLUMN TYPE_DE_LOCATION;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_DES_LOYERS DROP COLUMN VILLE;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_DES_LOYERS DROP COLUMN NUMERO_INSEE_DU_QUARTIER;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_DES_LOYERS DROP COLUMN NUMERO_ARRONDISSEMENT;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_DES_LOYERS DROP COLUMN ID_ADRESSE;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_DES_LOYERS DROP COLUMN ID_QUARTIERS;
ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".FAIT_ENCADREMENT_DES_LOYERS DROP COLUMN GEO_POINT_2D;

ALTER TABLE ANALYSE_IMMO_PARIS_2022."SCHEMA".DIM_ARRONDISSEMENTS DROP COLUMN CODE_POSTAL;

-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- Optimisation des données géographiques
------------------------------------------------------------------------------------------------------------------------------------------------------------
ALTER TABLE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_ARRONDISSEMENTS
ADD COLUMN LONGITUDE DECIMAL(10, 8),
ADD COLUMN LATITUDE DECIMAL(10, 8);

UPDATE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_ARRONDISSEMENTS
SET
    GEOM_Y_X = REPLACE(REPLACE(REPLACE(GEOM_Y_X, '{"lon":', ''), '"lat":', ''), '}', '');

UPDATE ANALYSE_IMMO_PARIS_2022.SCHEMA.DIM_ARRONDISSEMENTS
SET
    LONGITUDE = SPLIT_PART(GEOM_Y_X, ',', 1),
    LATITUDE = SPLIT_PART(GEOM_Y_X, ',', 2);



